version: "3.8"
services:

  redis:
    container_name: "redis"
    image: redis:alpine

    command: redis-server /usr/local/etc/redis/redis.conf --requirepass mypass

    ports:
      - "6379:6379"

    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/skofli/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped